language: c
compiler:
    - gcc
sudo: required
services:
    - docker

matrix:
    include:
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-16.04
          script:
              - ./scripts/build-ubuntu-docker.sh
              - docker images
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-16.04
          script:
              - ./scripts/build-ubuntu-docker-clang.sh
              - docker images
        - os: linux
          compiler: gcc
          env: BUILD_OS=18.04
          script:
              - ./scripts/build-ubuntu-18.4-docker.sh
              - docker images
        - os: linux
          compiler: gcc
          env: BUILD_OS=arch
          script:
              - ./scripts/build-arch-docker.sh
              - docker images

