language: c
compiler:
    - gcc
sudo: required
services:
    - docker
git:
    depth: false
matrix:
    include:
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc-7
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc-7 GEN=gen-8
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc-7 GEN=gen-9

script: ./scripts/run-build.sh

