language: c
compiler:
    - gcc
sudo: required
services:
    - docker

matrix:
    include:
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-16.4
          script:
              - ./configure
        - os: linux
          compiler: gcc
          env: BUILD_OS=18.04
          script:
              - ./configure
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-16.04
          script:
              - ./configure
        - os: linux
          compiler: gcc
          env: BUILD_OS=arch
          script:
              - ./configure

