language: c
compiler:
    - gcc
sudo: required
services:
    - docker

matrix:
    include:
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-16.04 COMPILER=gcc-5
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-16.04 COMPILER=clang-4.0

script: ./scripts/run-build.sh

